### ISSUE TITLE
[Docs] `postcss@latest` was added to the setup requirement but no relevant configuration was added

### ISSUE THREAD

**Issue by travis5491811** [nuxt-community/storybook#258]
Hello,
In [this commit](https://github.com/nuxt-community/storybook/commit/a2bb26daa336d73538080e536c1e061cc076e0c7) `postcss@latest` was added to the setup requirements but no relevant configuration was added. This results in the following:

```
You did not set any plugins, parser, or stringifier. Right now, PostCSS does nothing. Pick plugins for your case on https://www.postcss.parts/ and use them in postcss.config.js.
```

The project still appears to run okay. If it's not part of the minimum setup, why are we installing it? Should we be doing something else?

**Comment by Muvvekk** [comment]
Anyone on the dev team, have any updates on this? It doesn't really break the project, but the build turns into a spam board.

@travis5491811, did you manage to find some solution on the side of your project or warning keep showing up?

**Comment by Jikodis** [comment]
> Sorry for the late response.
> Using postcss8 is mandatory in new versions of Storybook.
> This issue will fix in the next version #277.

@farnabaz I see the issue is fixed, but it is unclear if a manual step of adding PostCSS to buildModules in the nuxt config is required. I see it in the bug notes on the releases page that maybe this is a manual step. In my case it was.

Additionally, the documentation seems to be up to date on the github repo readme, but https://storybook.nuxtjs.org/setup still mentions installing PostCSS as a dev dependency instead of adding it to buildModules in the nuxt config.

I would suggest adding to both the github documentation as well as https://storybook.nuxtjs.org/setup the manual step of adding PostCSS 8 to buildModules

Thanks for fixing this issue. It was causing a real headache and flooding our logs with warnings.

**Comment by drewbaker** [comment]
@Jikodis Did this also get your PostCSS plugins working?

**Comment by Jikodis** [comment]
> @Jikodis Did this also get your PostCSS plugins working?

Yes. Everything was working fine after the fix.
