### ISSUE TITLE
Reload TailwindCSS classes

### ISSUE THREAD

**Issue by arpadgabor** [nuxt-community/storybook#38]
I've just set up a project with TailwindCSS. While working on a component I noticed that classes do not reload on change. For example, if I wanted to modify a padding `p-2` to `p-4`, I have to completely reload Storybook. I've noticed this behavior in the example too.

Is there anything I can do to make them reload on save?

**Comment by farnabaz** [comment]
Could you create a reproduction sample on codesandbox?

**Comment by arpadgabor** [comment]
Well, yes. Actually this also seems to happen in the official [Tailwind example](https://codesandbox.io/s/github/nuxt-community/storybook/tree/master/examples/tailwind?file=/components/MyButton.vue). Try changing the padding on the button, save the file and reload the page. My guess is that in Storybook Tailwind will run purge-css by default.

I've found a workaround meanwhile so that I don't have to reload storybook by `Ctrl+S` in tailwind.config.js every time I do some changes to my classes.

**Comment by farnabaz** [comment]
I see. This happens because Nuxt run command in production mode and inside `tailwind.config.js` we enabled `purgeCSS` on production mode.

For the quick fix, you can manually set `NODE_ENV` to development. `NODE_ENV=development nuxt storybook` (on the windows you may need insatall [cross-env](https://www.npmjs.com/package/cross-env)

Also on the next release we'll fix `NODE_ENV` issue
